[project]
name = "latency"
version = "1.0.0"
description = "Tiny server that allows browsers to measure real latency."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "falcon>=4.0.2",
    "uvicorn>=0.34.3",
]
license = { file = "LICENSE" }
